### ISSUE TITLE
Port GuidUtil to string extensions

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Extensions#10]
_NOTE: Must be an andculture employee to work on this issue due to requiring access to private resources._

Extract and port GuidUtil to be string extensions as opposed to a static util class. See NFPA project in bitbucket. While it has unit tests, please review during the port and see if it requires more.

Once done, we will want to refactor this and other projects to leverage the new extension method approach.

**Comment by jebediahelliott** [comment]
Starting on this now

**Comment by wintondeshong** [comment]
Just noting that in the meantime, the GuidUtil itself has been ported.

@jebediahelliott if you no longer feel you'll have the time, which is totally fine, please unassign yourself.

**Comment by brandongregoryscott** [comment]
Published with [v0.4.6](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/releases/tag/v0.4.6)
