### ISSUE TITLE
Port UriUtils to string extensions

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.CSharp.Extensions#11]
_NOTE: Must be an andculture employee to work on this issue due to requiring access to private resources._

Extract and port UriUtils to be string extensions as opposed to a static util class. See NFPA project in bitbucket. While it has unit tests, please review during the port and see if it requires more.

Once done, we will want to refactor this and other projects to leverage the new extension method approach.

**Comment by joshuapeters** [comment]
@wintondeshong if this is still needed, happy to work on this today!

**Comment by wintondeshong** [comment]
> @wintondeshong if this is still needed, happy to work on this today!

@joshuapeters nice! go for it

**Comment by joshuapeters** [comment]
@brandongregoryscott @wintondeshong is it okay for me to close this issue? Or do one of you normally handle that?

**Comment by brandongregoryscott** [comment]
Usually we close it out with a comment of the published version it was released in. Published with [v0.4.2](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/releases/tag/v0.4.2), via #24
