### ISSUE TITLE
Port ExpressionExtensions

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.CSharp.Extensions#14]
_NOTE: Must be an andculture employee to work on this issue due to requiring access to private resources._

Extract and port `ExpressionExtensions` from the LMS project. While it has unit tests, please review during the port and see if it requires more.

Once done, we will want to refactor this and other projects to leverage the new extension method approach.

**Comment by wintondeshong** [comment]
Published with v0.2.0
