### ISSUE TITLE
Port IQueryable ordering extensions

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.CSharp.Extensions#26]
_NOTE: Must be an andculture employee to work on this issue due to requiring access to private resources._

From the LMS project, port over extension methods in `QueryableExtensions` (`OrderBy`, `ThenBy` and the private `OrderingHelper`) which allow for more dynamic sorting by string representations of properties & direction.

It does not look like this class has unit tests, so be sure to add coverage while porting.

**Comment by HeyKos** [comment]
@brandongregoryscott the `coverage/index.htm`  is not getting generated on this project when I run `and-cli dotnet-test`. Is this a known issue? I am trying to ensure that I am getting the appropriate coverage for these new extension methods.

**Comment by brandongregoryscott** [comment]
@HeyKos Good catch - looks like the current version of `coverlet.msbuild` we're running doesn't support .NET Core 3.1, and they recommend upgrading to 2.9.0:

https://github.com/coverlet-coverage/coverlet/issues/941

I'll bump the version we're on - we'll probably want to do this to a number of repos

**Comment by HeyKos** [comment]
Thanks for digging into that @brandongregoryscott .

**Comment by brandongregoryscott** [comment]
I'm having a hell of a time publishing this package right now (something with my dotnet setup got totally borked), so it'll be sitting in main for a bit, unpublished.

**Comment by brandongregoryscott** [comment]
Published with [v0.4.9](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/releases/tag/v0.4.9)
