### ISSUE TITLE
Port over reflection extension methods

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.CSharp.Extensions#35]
Methods that can be pulled into `TypeExtensions`:
- `bool HasProperty(Type type, string propertyName)`
- `object GetProperty(object src, string propertyName)`
- `PropertyInfo GetPropertyInfo(object src, string propertyName)`

**Comment by brandongregoryscott** [comment]
Published with [v0.4.8](https://github.com/AndcultureCode/AndcultureCode.CSharp.Extensions/releases/tag/v0.4.8)
