### ISSUE TITLE
Add Convenience method for safely getting types from an assembly

### ISSUE THREAD

**Issue by jhugs** [AndcultureCode/AndcultureCode.CSharp.Extensions#38]
Consider adding a convenience method to safely retrieve only loadable types from an assembly, see here as an example: 
https://stackoverflow.com/questions/11915389/assembly-gettypes-throwing-an-exception

**Comment by dzoccarato** [comment]
Hi, I've done something for this issue: #46 , do you want to take a look?

**Comment by dzoccarato** [comment]
Hi, I've done something for this. Do you want to have a look on it? #46
