### ISSUE TITLE
Code coverage isn't being generated - bump coverlet to 2.9.0

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.CSharp.Extensions#43]
As pointed out in #26, it looks like the version of coverlet we're on doesn't support .NET Core 3.1. We should bump the version to 2.9.0 to allow coverage reports to be generated with 3.1.

Documentation in the README.md file also needs to be updated to mention the correct command for generating test coverage `and-cli dotnet-test --coverage` as well as the file that's generated: `coverage.opencover.xml`

**Comment by HeyKos** [comment]
@brandongregoryscott I'll take this one since I was the one who first experienced it 😉 .

**Comment by HeyKos** [comment]
@brandongregoryscott it looks like the coverage report comes in the form of an XML (`coverage.opencover.xml`) now rather then `coverage/index.htm`. Unless I am missing something. Should I update the `README.md` to reflect this change?

**Comment by brandongregoryscott** [comment]
@HeyKos Ah, I thought you were already using the `--coverage` flag. Yeah - if there's existing documentation referencing `index.htm` instead of the xml coverage file, let's get that updated. Feel free to edit the body/title of this issue to reflect that (and we can open up issues on other C# repos for this change, too)

**Comment by HeyKos** [comment]
Works for me @brandongregoryscott. I've updated the description of this issue, and created issues on the other C# repos.

**Comment by HeyKos** [comment]
@brandongregoryscott I've submitted a PR to address this issue.

**Comment by brandongregoryscott** [comment]
Thank you @HeyKos!

**Comment by brandongregoryscott** [comment]
Closing this out - seems to have been resolved with that PR. Thanks again!
