### ISSUE TITLE
Change PackIconUrl to PackageIcon in csproj file

### ISSUE THREAD

**Issue by HeyKos** [AndcultureCode/AndcultureCode.CSharp.Extensions#44]
There is a warning regarding the nuget packing information when running the dotnet build: 

> "The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl"

Nuget nows wants icons to be embedded in the pack file (See issue: [352](https://github.com/NuGet/Home/issues/352))

Should be changed to something:

```
<PropertyGroup>
    ...
    <PackageIcon>icon.png</PackageIcon>
    ...
</PropertyGroup>

<ItemGroup>
    <None Include="icon.png" Pack="true" Visible="false" PackagePath="" />
</ItemGroup>
```

**Comment by brandongregoryscott** [comment]
Yeah, definitely seen this before - we'll probably want this issue on each of our packaged C# repos.

**Comment by dzoccarato** [comment]
Hi @brandongregoryscott , @HeyKos 
I did something for this. Would you like to take a look?
Thanks
